# Generated by Django 4.0.3 on 2022-04-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bid_id_alter_category_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[(0, 'Closed'), (1, 'Active')], default=1, max_length=1),
        ),
    ]
