# Generated by Django 4.0.3 on 2022-04-03 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_bid_created_alter_comment_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='winning_bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
